### ISSUE TITLE
pull requests    Adding Multi-Graph Random   增加多图循环

### ISSUE THREAD

**Issue by yoloyi** [formulahendry/vscode-ycy#18]
增加多图循环

=== 
* 增加多图循环，
* 鼓励的声音在研究
vscode中播放声音不怎么好搞。尝试了几种方式，不行。需要下载dll或者其他插件。

**Comment by suanrong** [comment]
给你点个赞，啥时候pull requests 能接受啊

**Comment by yoloyi** [comment]
@suanrong 更新了。你可以看最新的readme
