### ISSUE TITLE
vscode装不了，报错

### ISSUE THREAD

**Issue by zhouzhili** [formulahendry/vscode-ycy#4]
![image](https://user-images.githubusercontent.com/14259932/55875267-470a7d00-5bc7-11e9-883b-b8b1d195a62b.png)

**Comment by formulahendry** [comment]
VS Code 版本是否为最新？

**Comment by sanfengzhanggif** [comment]
升级一下vscode就好啦

**Comment by zhouzhili** [comment]
是的，升级到最新版就可以了
