### ISSUE TITLE
差评！！只有一个杨超越，我要好多好多ycy

### ISSUE THREAD

**Issue by zhang435** [formulahendry/vscode-ycy#6]
题主介意我push个随机选图进来么

**Comment by gdh1995** [comment]
顶楼上。一张太少了。

PS：我个人更喜欢能自动消除的弹窗/提醒框方式。

**Comment by liyishuai** [comment]
#2, once fixed, should resolve this issue.

**Comment by zhang435** [comment]
@liyishuai 看看能不能连上在线图库TOT

**Comment by HungryBird** [comment]
要一个摸摸哒

**Comment by deviluncle** [comment]
什么时候更新图片库啊

**Comment by gdh1995** [comment]
@liyishuai 没自动切换也不好玩，太麻烦啊（伸手

**Comment by formulahendry** [comment]
最新版本已支持自定义图片。谢谢 @yoloyi ！
