### ISSUE TITLE
哥哥，我想抱走源码，换个图片可以吗

### ISSUE THREAD

**Issue by font-end-newbie** [formulahendry/vscode-ycy#9]

**Comment by o-u-p** [comment]
前端代码不是随便换？
![Screenshot from 2019-04-11 13-35-28](https://user-images.githubusercontent.com/22117027/55933120-c4350100-5c5e-11e9-9a39-2414d68cba80.png)

**Comment by malone6** [comment]
![image](https://user-images.githubusercontent.com/15245112/55943923-20594e80-5c7a-11e9-8073-40708ee13624.png)

**Comment by dengxiaozhen** [comment]
@o-u-p @malone6 大佬，请教下怎么修改图片

**Comment by malone6** [comment]
> @o-u-p @malone6 大佬，请教下怎么修改图片
1.找到这个路径去替换图片就行了，下图是我linux的路径，win的话应该也一样
![image](https://user-images.githubusercontent.com/15245112/56019074-53611800-5d36-11e9-8967-4e39e9990e98.png)
2. 修改代码去渲染其他名称的图片，还可以做一个随机的，哈哈

**Comment by dengxiaozhen** [comment]
> > @o-u-p @malone6 大佬，请教下怎么修改图片
> > 1.找到这个路径去替换图片就行了，下图是我linux的路径，win的话应该也一样
> > ![image](https://user-images.githubusercontent.com/15245112/56019074-53611800-5d36-11e9-8967-4e39e9990e98.png)
> 
> 1. 修改代码去渲染其他名称的图片，还可以做一个随机的，哈哈

多谢大佬指点
